### PR TITLE
Delete report award messages after a while and format code by isort and black

### LINKED ISSUE #129: Delete report award messages after a while
I suggest delete messages about awarding reports after a while, because it's useless to leave these messages for a long time

### LINKED ISSUE #131: Format code by using isort, black and ruff

### PR DESCRIPTION
**Pull request by Desiders**
Closes #129, closes #131

I also used the isort and black linters to format the code. Config for black has been created and small changes for isort.

### CODE REVIEW

**Comment by Desiders** [comment]
Connect this PR with #131

**Comment by Desiders** [comment]
Close #131

**Comment by Lamroy95** [comment]
Can you please split this PR? I suggest to separate:
1. The actual feature
2. Formatting the whole project

This will reduce the changes and make it easy to review the changes related to the feature

**Comment by Desiders** [comment]
> Can you please split this PR? I suggest to separate:
> 
>     1. The actual feature
> 
>     2. Formatting the whole project
> 
> 
> This will reduce the changes and make it easy to review the changes related to the feature

Okey

**Comment by Desiders** [comment]
Recreate #134

**Pull request closed without merging**
